swagger: '2.0'
info:
  description: API for email verification and sending reset code
  version: "1.0.0"
  title: Email Verification API
host: localhost:3005
basePath: /
schemes:
  - http
paths:
  /email/check-email:
    post:
      summary: Check if email exists and send reset code
      parameters:
        - in: body
          name: email
          description: User's email
          required: true
          schema:
            type: object
            properties:
              email:
                type: string
      responses:
        200:
          description: User ID returned and reset code sent
          schema:
            type: object
            properties:
              userId:
                type: string
        404:
          description: Email not found
        500:
          description: Error sending email
definitions:
  User:
    type: object
    properties:
      email:
        type: string
      password:
        type: string
